accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('ai_check/', ai_check, name='ai_check'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zeronine.urls')),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

join/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('join_create/<int:id>/', join_create, name='join_create'),
    ]

mypage/urls.py
from django.urls import path
import mypage.views

urlpatterns = [
    path('mypage_list/', mypage.views.mypage_list, name='mypage_list'),
    path('profile/delete/', mypage.views.profile_delete_view, name='profile_delete'),
    path('mypage_pwchange/', mypage.views.password_edit_view, name='mypage_pwchange'),
    path('mypage_joinlist/', mypage.views.mypage_joinlist, name='mypage_joinlist'),
    path('mypage_zzimlist/', mypage.views.mypage_zzimlist, name='mypage_zzimlist'),
    path('zzim_delete/<int:pk>/', mypage.views.zzim_delete, name='zzim_delete'),
    path('mypage_uploadlist/', mypage.views.mypage_uploadlist, name='mypage_uploadlist'),
    path('mypage_delete/<int:pk>/', mypage.views.mypage_delete, name='mypage_delete'),
    ]

post/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('post/', post, name='post'),
    path('post_write/', post_write, name='post_write'),
    path('post_detail/<int:pk>/', post_detail, name='post_detail'),
    path('post_delete/<int:pk>/', post_delete, name='post_delete'),
    path('post_modify/<int:pk>/', post_modify, name='post_modify'),
    path('comment_create/<int:article_pk>', comment_create, name='comment_create'),
    path('comment_delete/<int:comment_pk>', comment_delete, name='comment_delete'),
    path('search/', search, name='search'),
]

product/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('product_upload/', product_upload, name='product_upload'),
    path('product_search/', product_search, name='product_search'),
    ]

zeronine/urls.py
from django.urls import path, include
from .views import *

app_name = 'zeronine'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<category_slug>/', product_in_category, name='product_in_category'),
    path('<int:id>/<product_slug>/', product_detail, name='product_detail'),
    path('accounts/', include('accounts.urls')),
    path('post/', include('post.urls')),
    path('product/', include('product.urls')),
    path('join/', include('join.urls')),
    path('zzim/', include('zzim.urls')),
    path('mypage/', include('mypage.urls')),
]

zeronine/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse

# 회원
class Member(AbstractUser):
    username = models.CharField(primary_key=True, max_length=20, verbose_name='아이디')
    name = models.CharField(max_length=20, verbose_name='이름', default='')
    password = models.CharField(max_length=64, verbose_name='비밀번호')
    phone = models.CharField(max_length=64, verbose_name='전화번호')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = ('Member')
        verbose_name_plural = ('Members')

# 카테고리
class Category(models.Model):
    category_code = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, allow_unicode=True)

    class Meta:
        ordering =['category_code']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('zeronine:product_in_category', args=[self.slug])

# 상품
class Product(models.Model):
    product_code = models.AutoField(primary_key=True)
    username = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='username')
    category_code = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=False, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    benefit = models.TextField()
    detail = models.TextField()
    target_price = models.IntegerField()
    start_date = models.DateField()
    due_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    kakao_link = models.CharField(max_length=200, default='')

    class Meta:
        ordering = ['product_code']
        index_together = [['product_code', 'slug']]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('zeronine:product_detail', args=[self.product_code, self.slug])

    def get_total(self):
        join_list = list(JoinDetail.objects.filter(join_code__product_code_id=self.product_code).values_list('price', flat=True))
        total_price = sum(list(filter(None, join_list)))
        return total_price

    def option_exists(self):
        options = self.option.all()
        if options.exists():
            return True
        else:
            return False


class Post(models.Model):
    post_code = models.AutoField(primary_key=True)
    username = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='username')
    title = models.CharField(max_length=64)
    content = models.TextField()
    register_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['post_code']

# 댓글(댓글코드, 게시글코드(fk), 아이디(fk), 내용, 등록날짜)
class Comment(models.Model):
    comment_code = models.AutoField(primary_key=True)
    post_code = models.ForeignKey(Post, on_delete=models.CASCADE, db_column='post_code')
    username = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='username')
    content = models.TextField()
    register_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['register_date']

# Zzim 모델부터 새로 추가하려는 모델들 입니다.

# 찜하기(찜코드, 아이디(fk), 상품코드(fk))
class Zzim(models.Model):
    zzim_code = models.AutoField(primary_key=True)
    username = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='username')
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, db_column='product_code')

    def __str__(self):
        return str(self.zzim_code)

    class Meta:
        ordering = ['zzim_code']

# 상품이미지(이미지코드, 상품코드(fk), 이미지경로)
class Photo(models.Model):
    photo_code = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, db_column='product_code')
    photo = models.ImageField(upload_to="photos/%Y%m%d")

    def __str__(self):
        return str(self.photo_code)

    class Meta:
        ordering = ['photo_code']


# 옵션(옵션코드, 옵션명, 상품코드(fk))
class Option(models.Model):
    option_code = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, db_column='product_code', related_name='option')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['option_code']

# 옵션값(옵션값코드, 옵션값명, 옵션코드(fk), 상품코드(fk))
class Value(models.Model):
    value_code = models.AutoField(primary_key=True)
    option_code = models.ForeignKey(Option, on_delete=models.CASCADE, db_column='option_code')
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, db_column='product_code')
    name = models.CharField(max_length=32)
    extra_cost = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['value_code']

# 옵션지정상품(옵션지정상품코드, 상품코드(fk), 가격, 참여수량)
class Designated(models.Model):
    designated_code = models.AutoField(primary_key=True)
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, db_column='product_code')
    price = models.IntegerField()
    rep_price = models.BooleanField(default=True)

    class Meta:
        ordering = ['designated_code']

    def __str__(self):
        return str(self.designated_code)

# 상품옵션구성(상품옵션구성코드, 옵션지정상품코드, 옵션값코드)
class Element(models.Model):
    element_code = models.AutoField(primary_key=True)
    designated_code = models.ForeignKey(Designated, on_delete=models.CASCADE, db_column='designated_code')
    value_code = models.ForeignKey(Value, on_delete=models.CASCADE, db_column='value_code', null=True, blank=True)

    class Meta:
        ordering = ['element_code']

    def __str__(self):
        return str(self.element_code)

# 참여(참여코드, 아이디(fk), 상품코드(fk), 수량)
class Join(models.Model):
    join_code = models.AutoField(primary_key=True)
    username = models.ForeignKey(Member, on_delete=models.CASCADE, db_column='username')
    product_code = models.ForeignKey(Product, on_delete=models.CASCADE, db_column='product_code')
    part_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.join_code)

    class Meta:
        ordering = ['join_code']

#참여상세(참여상세코드, 수량, 가격, 참여코드, 옵션지정상품코드)
class JoinDetail(models.Model):
    joindetail_code = models.AutoField(primary_key=True)
    join_code = models.ForeignKey(Join, on_delete=models.CASCADE, db_column='join_code')
    value_code = models.ForeignKey(Value, on_delete=models.CASCADE, db_column='value_code', null=True, blank=True)
    designated_code = models.ForeignKey(Designated, on_delete=models.CASCADE, null=True, blank=True, db_column='designated_code')
    quantity = models.IntegerField(null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.joindetail_code)

    class Meta:
        ordering = ['joindetail_code']

zeronine/forms.py
from django import forms

from zeronine.models import *

class AddProductForm(forms.Form):
    quantity = forms.IntegerField()
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class DetailForm(forms.Form):
    select_option = forms.ModelChoiceField(error_messages={'required': "옵션을 선택하세요."}, label="옵션", queryset=Value.objects.all())
    designated_code = forms.CharField()

zeronine/views.py
from datetime import date, datetime
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views import View

from zeronine.forms import *
from zeronine.models import *

def product_in_category(request, category_slug=None):
    current_category = None
    categories = Category.objects.all()
    join = Join.objects.all()
    join_detail = JoinDetail.objects.all()
    products = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    designated_low = Designated.objects.filter(rep_price='True').order_by('price')
    designated_high = Designated.objects.filter(rep_price='True').order_by('-price')
    product_due_date = Product.objects.all().order_by('due_date')
    product_created_at = Product.objects.all().order_by('-created_at')

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category_code=current_category)


    return render(request, 'zeronine/list.html', {'current_category': current_category,
                                                  'categories':categories,
                                                  'products':products,
                                                  'join':join,
                                                  'join_detail':join_detail,
                                                  'designated_object':designated_object,
                                                  'designated_high': designated_high,
                                                  'designated_low': designated_low,
                                                  'product_due_date':product_due_date,
                                                  'product_created_at':product_created_at,
                                                  })

def product_detail(request, id, product_slug=None):
    current_category = None
    categories = Category.objects.all()
    product = get_object_or_404(Product, product_code=id, slug=product_slug)
    product_object = Product.objects.all()
    designated_object = Designated.objects.filter(rep_price='True')
    designated_object2 = Designated.objects.filter(rep_price='False', product_code=id)
    element_object = Element.objects.all()
    photo_object = Photo.objects.all()
    option_object = Option.objects.all()
    value_object = Value.objects.all()
    delta = product.due_date - datetime.now().date()
    delta_result = delta.days


    return render(request, 'zeronine/detail.html', {'product': product,
                                                    'product_object':product_object,
                                                    'current_category': current_category,
                                                    'categories': categories,
                                                    'designated_object': designated_object,
                                                    'designated_object2':designated_object2,
                                                    'element_object': element_object,
                                                    'photo_object':photo_object,
                                                    'option_object': option_object,
                                                    'value_object': value_object,
                                                    'delta': delta,
                                                    'delta_result': delta_result,
                                                    })

zeronine/templates/base.html
<!DOCTYPE html>
<html lang="en">

<style>

@import url('https://fonts.googleapis.com/css2?family=Hahmlet:wght@200;400&family=Noto+Sans+KR&display=swap');

* {
    font-family: 'Noto Sans KR', sans-serif;
}

.footer_logo {
    font-family: 'Questrial', sans-serif;
    font-size: 50px;
}

@media screen and (min-width: 601px) {
  .footer {
        height: 280px;
  }
}

@media screen and (min-width: 600px) {
  .footer {
       height: 200px;
  }
}


@media screen and (min-width: 601px) {
  .footer_logo {
        font-size: 50px;
        margin-left: 230px;
  }
}

@media screen and (max-width: 600px) {
  .footer_logo {
      font-size: 30px;
      margin-left: 25px;
  }
}

@media screen and (min-width: 601px) {
  .footer_p {
        font-size: 15px;
        margin-left: 230px;
  }
}

@media screen and (max-width: 600px) {
  .footer_p {
      font-size: 11px;
       margin-left: 25px;
  }
}

@media screen and (min-width: 601px) {
  .navbar-brand {
      width: 170px;
  }
}

@media screen and (max-width: 600px) {
  .navbar-brand {
      width: 120px;
  }
}

.search {
  display: flex;
  align-items: center;
  transition: all 0.3s ease 0.5s;
  background: #fff;
}
.search .icon {
  width: 16px;
  cursor: pointer;
  height: 16px;
  margin: 16px;
  position: relative;
  transform: rotate(90deg) translate(-10%, -10%);
  transition: all 0.3s ease 0.6s;
}
.search .icon:before {
  content: "";
  position: absolute;
  border-radius: 50%;
  border: 2px solid #4C515E;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  display: block;
  transition: all 0.3s ease 0s;
}
.search .icon span {
  display: block;
  top: 35%;
  left: 35%;
  width: 2px;
  height: 2px;
  border-radius: 1px;
  margin: -1px 0 0 -1px;
  position: absolute;
  transition: background 0s ease 0s;
}

.search .icon span:before {
  right: 0;
}
.search .icon span:after {
  left: 0;
}
.search .icon span svg {
  display: block;
  fill: none;
  stroke-linecap: round;
  stroke-width: 5px;
  stroke: #4C515E;
  width: 15px;
  height: 15px;
  position: absolute;
  left: 0;
  top: 0;
  stroke-dasharray: 47;
  stroke-dashoffset: 67;
  transition: all 0.4s ease 0.31s, opacity 0.1s ease 0.4s, stroke 0.4s ease 0s;
}
.search .field {
  position: relative;
  width: 0;
  transition: all 0.5s cubic-bezier(0.51, 0.92, 0.24, 1.15) 0.5s;
}
.search .field input {
  font-size: inherit;
  line-height: inherit;
  padding: 0 24px 0 0;
  border: 0;
  display: block;
  font-family: inherit;
  position: absolute;
  background: #fff;
  -webkit-appearance: none;
  top: 0;
  width: 100%;
  opacity: 0;
  z-index: 1;
  visibility: hidden;
  transition: all 0s ease 0s;
  margin: 0;
  vertical-align: middle;
  text-transform: none;
}
.search .field input:focus {
  outline: none;
}
.search .field input::-webkit-input-placeholder {
  color: #212533;
}
.search .field input:-moz-placeholder {
  color: #212533;
}
.search .field input::-moz-placeholder {
  color: #212533;
}
.search .field input:-ms-input-placeholder {
  color: #212533;
}
.search .field > div {
  white-space: nowrap;
  color: #212533;
  display: flex;
}
.search .field > div span {
  opacity: 0;
  line-height: 22px;
  display: block;
  visibility: hidden;
  transform: translate(0, 12px);
  transition: all 0.4s ease;
}
.search .field > div span:nth-child(1) {
  transition-delay: 0.4s;
}
.search .field > div span:nth-child(2) {
  transition-delay: 0.2s;
}
.search .field > div span:nth-child(3) {
  transition-delay: 0s;
}
.search.open {
  border-radius: 8px;
  transition-delay: 0s;
  box-shadow: 0 10px 36px -2px rgba(0, 0, 0, 0.18);
}
.search.open .icon {
  transform: rotate(0deg) translate(0, 0);
  transition-delay: 0s;
}
.search.open .icon:before {
  border-color: #212533;
}
.search.open .icon span svg {
  stroke: #212533;
  transition-delay: 0s;
}
.search.open .field {
  transition-delay: 0s;
  width: 200px;
}
.search.open .field > div span {
  opacity: 1;
  visibility: visible;
  transform: translate(0, 0);
}
.search.open .field > div span:nth-child(1) {
  transition-delay: 0.4s;
}
.search.open .field > div span:nth-child(2) {
  transition-delay: 0.45s;
}
.search.open .field > div span:nth-child(3) {
  transition-delay: 0.5s;
}
.search.open .field input {
  opacity: 1;
  visibility: visible;
  transition-delay: 0.75s;
}
.search.loading .icon span {
  background: #212533;
  -webkit-animation: rotate 1s infinite ease 0.8s;
          animation: rotate 1s infinite ease 0.8s;
  transition-delay: 0.4s;
}
.search.loading .icon span svg {
  transition-delay: 0s;
  stroke-dasharray: 48;
  stroke-dashoffset: 139;
  opacity: 0;
  transition: all 0.4s ease 0s, opacity 0s ease 0.4s;
}
.search.loading .icon span:before, .search.loading .icon span:after {
  opacity: 1;
  transition-delay: 0.4s;
}
.search.loading .icon span:before {
  transform: translate(-4px, 0);
}
.search.loading .icon span:after {
  transform: translate(4px, 0);
}

@-webkit-keyframes rotate {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

@keyframes rotate {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

*:before, *:after {
  box-sizing: inherit;
}

.dribbble {
  position: fixed;
  display: block;
  right: 20px;
  bottom: 20px;
  opacity: 0.5;
  transition: all 0.4s ease;
}
.dribbble:hover {
  opacity: 1;
}
.dribbble img {
  display: block;
  height: 36px;
}
</style>
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- 로고 폰트 url -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Questrial&display=swap" rel="stylesheet">

    {% block script %}
    {% endblock %}

    {% block style %}
    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'main.css' %}">

        {% if not user.is_authenticated %}
        <div class="notice" style="width: 100%; height: 40px; background-color: #283c16; text-align: center">
            <a href="{% url 'zeronine:ai_check' %}" style="text-decoration:none; justify-content:center; color: white; text-align: center; line-height: 35px;">지금 가입하고 저렴하게 구입하세요!&nbsp;&nbsp;&nbsp;&nbsp;➜</a>
        </div>
        {% else %}
         <div style="width: 100%; height: 40px; background-color: #283c16; text-align: center">
             <a href="{% url 'zeronine:logout' %}" style="text-decoration:none; justify-content:center; color: white; text-align: center; line-height: 35px;"><b>{{user.username}}</b>님, 환영합니다.</a>
        </div>
        {% endif %}

    <div class="navbar navbar-expand-md navbar-light" style="text-align: center">
        <a class="navbar-brand" href="/" style="text-align: center; text-decoration: none;"><img class="zn_logo" src="/static/img/zeronine_logo_image.png" style="width: 170px; margin-top: -25px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>

    <nav class="navbar navbar-expand-lg">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto" style="margin: auto; margin-top: -30px;">

        <li class="nav-item">
          <a class="nav-link" href="/" class="nav-link">전체상품</a>
        </li>

        {% for c in categories %}
        <li class="nav-item">
            <a class="nav-link"  href="{{c.get_absolute_url}}" class="nav-link {% if current_category.slug == c.slug %} active {% endif %}" >{{c.name}}</a></a>
        </li>
        {% endfor %}

        <li class="nav-item"><a href="{% url 'zeronine:post' %}" class="nav-link">자유게시판</a></li>
            {% csrf_token %}
        <li class="nav-item">
            {% if user.is_authenticated %}
        <li class="nav-item">
            <!--로그인 후 검색기능-->
            <form action="{% url 'zeronine:product_search' %}" autocomplete="on" method="get">
            {% csrf_token %}
            <div class="search">
                <div class="icon" >
                    <span>
                        <svg viewBox="0 0 40 40">
                            <path d="M3,3 L37,37"></path>
                        </svg>
                    </span>
                </div>
                <div class="field">
                    <input type="text" placeholder="상품을 입력하세요..." name="q" value="{{q}}">
                </div>
            </div>
              </form>
        <li class="nav-item"><a href="{% url 'zeronine:mypage_list' %}" class="nav-link"><img src="/static/img/mypage2.png" style="width: 20px;"></a></li>
            {% else %}
        <li class="nav-item">
            <!--로그인 전 검색기능-->
            <form action="{% url 'zeronine:product_search' %}" autocomplete="on" method="get">
            {% csrf_token %}
            <div class="search">
                <div class="icon">
                    <span>
                        <svg viewBox="0 0 40 40">
                            <path d="M3,3 L37,37"></path>
                        </svg>
                    </span>
                </div>
                <div class="field">
                    <input type="text" placeholder="상품을 입력하세요..." name="q" value="{{q}}">
                </div>
            </div>
              </form>
        <li class="nav-item"><a href="{% url 'zeronine:login' %}" class="nav-link" style="color: black;"><img src="/static/img/mypage2.png" style="width: 20px;"></a></li>
            {% endif %}
      </li>
    </ul>
  </div>
</nav>
<script>
    $(document).ready(function() {

    $('.search').each(function() {
        var self = $(this);
        var div = self.children('.field');
        var placeholder = div.children('input').attr('placeholder');
        var placeholderArr = placeholder.split(/ +/);
        if(placeholderArr.length) {
            var spans = $('<div />');
            $.each(placeholderArr, function(index, value) {
                spans.append($('<span />').html(value + '&nbsp;'));
            });
            div.append(spans);
        }
        self.click(function() {
            self.addClass('open');
            setTimeout(function() {
                self.find('input').focus();
                self.find('input').on('keyup', function() {
                    self.toggleClass('loading', (self.find('input').val().toString().length > 3));
                });
            }, 750);
        });
        $(document).click(function(e) {
            if(!$(e.target).is(self) && !jQuery.contains(self[0], e.target)) {
                self.removeClass('open loading');
                setTimeout(function() {
                    self.find('input').val('');
                }, 400);
            }
        });
    });

});

</script>
        {% block content %}
        {% endblock %}

</head>
     <footer class="footer" style=" width: 100%; height: 280px; padding: 15px; text-align: left; background-color: #F2F2F2; margin-top: 100px;">
         <p class="footer_logo" style="margin-top: 40px;">ZERONINE</p>
         <p class="footer_p">ZERONINE ⓒ 2021 ALL RIGHTS RESERVED.</p>
         <p class="footer_p" style="color: #6E6E6E;">제로나인 | 주소: 서울특별시 성동구 살곶이길 200 한양여자대학교 | 대표자명: 심혜원 <br>
             개인정보보호책임자: 박지수 | 메일: zeronine0900@gmail.com | CALL: 02-2290-2114</p>
     </footer>
</html>